export const RESET = 'RESET'
export const REGISTER = 'REGISTER'

export const LOGIN = 'LOGIN'
export const LOGINCOMPLETE = 'LOGINCOMPLETE'

export const SAVECHANGES = 'SAVECHANGES'
export const SAVECOMPLETE = 'SAVECOMPLETE'

export const STARTLOADING = 'STARTLOADING'
export const ENDLOADING = 'ENDLOADING'

export const GETTYPE = 'GETTYPE'
export const GETTYPESUCCESS = 'GETTYPESUCCESS'

export const TYPEEDIT = 'TYPEEDIT'

export const EDITTYPE = 'EDITTYPE'

export const DELETETYPE = 'DELETETYPE'

export const GETDISH = 'GETDISH'
export const GETDISHCOMPLETE = 'GETDISHCOMPLETE'

export const DISHEDIT = 'DISHEDIT'

export const EDITDISH = 'EDITDISH'

export const DELETEDISH = 'DELETEDISH'

export const GETORDER = 'GETORDER'
export const GETORDERCOMPLETE = 'GETORDERCOMPLETE'

export const EDITORDER = 'EDITORDER'

export const GETCOMPLETE = 'GETCOMPLETE'
export const GETCOMPLETEDONE = 'GETCOMPLETEDONE'

export const SETHEIGHT = 'SETHEIGHT'
export const SETCOMPHEIGHT = 'SETCOMPHEIGHT'